version: '3'

services:
    cti-nginx:
        container_name: cti-nginx
        build:
            context: ./conf
            dockerfile: dockerfile-nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 8007:80
        depends_on:
            - cti-php
        volumes:
            - ./nginx/logs:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./files/:/code
        networks:
           - cti-network
    cti-php:
        container_name: cti-php
        build:
            context: ./conf
            dockerfile: dockerfile-php
        image: php:latest
        restart: unless-stopped
        volumes:
            - ./files/:/code
        ports:
            - 9000
        networks:
            - cti-network
networks:
    cti-network:
        driver: bridge
